"""Lazy in-memory index of the quote corpus for runtime lookups.

The PHP image generator (`image-gen/quote_to_image.php`) bakes quote text +
attribution into the PNGs and names them ``quote_{HHMM}_{idx}_credits.png``
where ``idx`` is the per-time-bucket position in the source CSV. This
module gives us the inverse — given an image filename, return
``{quote, author, title, time}`` so the PWA hero card can render the quote
in HTML rather than read text out of a baked PNG.

Loaded once at first lookup; ~5000 rows, well under 1MB resident.
"""

from __future__ import annotations

import csv
import os
import re
from functools import lru_cache
from pathlib import Path

_PROJECT_ROOT = Path(__file__).resolve().parents[1]
_CORPUS_PATH = Path(
    os.environ.get(
        "LITCLOCK_CORPUS_CSV",
        str(_PROJECT_ROOT / "image-gen" / "litclock_annotated.csv"),
    )
)

# Image filename forms generated by quote_to_image.php:
#   quote_{HHMM}_{idx}.png                       (image)
#   quote_{HHMM}_{idx}_credits.png               (metadata variant)
#   quote_{HHMM}_{idx}_nsfw.png                  (NSFW image)
#   quote_{HHMM}_{idx}_nsfw_credits.png          (NSFW metadata variant)
_FILENAME_RE = re.compile(r"^quote_(?P<hhmm>\d{4})_(?P<idx>\d+)(?:_nsfw)?(?:_credits)?\.png$")


def _strip_outer_quotes(value: str) -> str:
    """Mirror PHP's quote handling for the runtime case. CSV fields wrapped
    in `""` get unwrapped; doubled `""` inside the quoted field collapse
    to single `"` per CSV convention. Python's csv module already handles
    the inner unescaping; this exists for the rare case where a row was
    written without proper csv quoting."""
    value = value.strip()
    if len(value) >= 2 and value[0] == '"' and value[-1] == '"':
        value = value[1:-1]
    return value.replace('""', '"').strip()


@lru_cache(maxsize=4)
def _index_for_mtime(mtime_ns: int) -> dict[tuple[str, int], dict[str, str]]:
    """Build an index keyed by ``(HHMM, idx) → metadata``.

    Mirrors PHP's per-time-bucket counter in `quote_to_image.php`: the
    `imagenumber` resets to 0 when the time field changes and increments
    otherwise. NSFW rows count toward the same counter (they get a
    `_nsfw` suffix in the filename but share the bucket index).

    Caching is keyed by the CSV's mtime_ns, not by argument identity, so
    a `corpus_edit ship` (which rewrites the CSV) auto-invalidates the
    cache without restarting control_server (adversarial /review on M2
    caught this — long-running control_server would serve stale
    attribution after a corpus edit until restart). lru_cache(maxsize=4)
    keeps the last few mtimes so a brief mtime flap doesn't thrash the
    parser.
    """
    index: dict[tuple[str, int], dict[str, str]] = {}
    if not _CORPUS_PATH.exists():
        return index

    previous_hhmm: str | None = None
    image_number = 0

    with _CORPUS_PATH.open(newline="", encoding="utf-8") as f:
        reader = csv.reader(f, delimiter="|")
        for row in reader:
            if len(row) < 5:
                continue
            time_str = row[0]
            # Expect "HH:MM"; defensive against malformed rows.
            if len(time_str) != 5 or time_str[2] != ":":
                continue
            hhmm = time_str[:2] + time_str[3:]
            if hhmm == previous_hhmm:
                image_number += 1
            else:
                image_number = 0
                previous_hhmm = hhmm

            index[(hhmm, image_number)] = {
                "time": time_str,
                "timestring": row[1].strip(),
                "quote": _strip_outer_quotes(row[2]),
                "title": row[3].strip(),
                "author": row[4].strip(),
            }
    return index


def _current_mtime_ns() -> int:
    """Return the corpus CSV's mtime in nanoseconds, or 0 if it doesn't
    exist. Used as the lru_cache key so the index auto-invalidates on
    corpus edit. Per-call stat is microseconds — much cheaper than CSV
    re-parse (~100-300ms on Pi Zero)."""
    try:
        return _CORPUS_PATH.stat().st_mtime_ns
    except OSError:
        return 0


def _index() -> dict[tuple[str, int], dict[str, str]]:
    return _index_for_mtime(_current_mtime_ns())


def lookup_by_filename(filename: str) -> dict[str, str] | None:
    """Look up quote metadata by image filename. Returns ``None`` if not
    found (corpus missing, malformed name, or out-of-range idx)."""
    name = os.path.basename(filename)
    m = _FILENAME_RE.match(name)
    if not m:
        return None
    hhmm = m.group("hhmm")
    idx = int(m.group("idx"))
    return _index().get((hhmm, idx))


def reset_cache() -> None:
    """Test hook — clears the lru_cache so each test sees a fresh index.
    Without this, tests that monkeypatch the corpus path will see the
    stale index from the first call."""
    _index_for_mtime.cache_clear()
